services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=enclave_db
      - POSTGRES_USER=enclave_user
      - POSTGRES_PASSWORD=enclave_password
    ports:
      - 5432:5432
