services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=enclave
      - POSTGRES_USER=enclave
      - POSTGRES_PASSWORD=enclave
    ports:
      - 5432:5432
