// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.5
// source: task.proto

package proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FunctionIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *ArtifactIdentifier    `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Interface     string                 `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionIdentifier) Reset() {
	*x = FunctionIdentifier{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionIdentifier) ProtoMessage() {}

func (x *FunctionIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionIdentifier.ProtoReflect.Descriptor instead.
func (*FunctionIdentifier) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *FunctionIdentifier) GetArtifact() *ArtifactIdentifier {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *FunctionIdentifier) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *FunctionIdentifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// A WIT value — represents any value in the WebAssembly Component Model type
// system. See https://component-model.bytecodealliance.org/design/wit.html
type Val struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Val_BoolVal
	//	*Val_S8Val
	//	*Val_U8Val
	//	*Val_S16Val
	//	*Val_U16Val
	//	*Val_S32Val
	//	*Val_U32Val
	//	*Val_S64Val
	//	*Val_U64Val
	//	*Val_F32Val
	//	*Val_F64Val
	//	*Val_CharVal
	//	*Val_StringVal
	//	*Val_ListVal
	//	*Val_TupleVal
	//	*Val_OptionVal
	//	*Val_ResultVal
	//	*Val_RecordVal
	//	*Val_VariantVal
	//	*Val_EnumVal
	//	*Val_FlagsVal
	Value         isVal_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Val) Reset() {
	*x = Val{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Val) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Val) ProtoMessage() {}

func (x *Val) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Val.ProtoReflect.Descriptor instead.
func (*Val) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *Val) GetValue() isVal_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Val) GetBoolVal() bool {
	if x != nil {
		if x, ok := x.Value.(*Val_BoolVal); ok {
			return x.BoolVal
		}
	}
	return false
}

func (x *Val) GetS8Val() int32 {
	if x != nil {
		if x, ok := x.Value.(*Val_S8Val); ok {
			return x.S8Val
		}
	}
	return 0
}

func (x *Val) GetU8Val() uint32 {
	if x != nil {
		if x, ok := x.Value.(*Val_U8Val); ok {
			return x.U8Val
		}
	}
	return 0
}

func (x *Val) GetS16Val() int32 {
	if x != nil {
		if x, ok := x.Value.(*Val_S16Val); ok {
			return x.S16Val
		}
	}
	return 0
}

func (x *Val) GetU16Val() uint32 {
	if x != nil {
		if x, ok := x.Value.(*Val_U16Val); ok {
			return x.U16Val
		}
	}
	return 0
}

func (x *Val) GetS32Val() int32 {
	if x != nil {
		if x, ok := x.Value.(*Val_S32Val); ok {
			return x.S32Val
		}
	}
	return 0
}

func (x *Val) GetU32Val() uint32 {
	if x != nil {
		if x, ok := x.Value.(*Val_U32Val); ok {
			return x.U32Val
		}
	}
	return 0
}

func (x *Val) GetS64Val() int64 {
	if x != nil {
		if x, ok := x.Value.(*Val_S64Val); ok {
			return x.S64Val
		}
	}
	return 0
}

func (x *Val) GetU64Val() uint64 {
	if x != nil {
		if x, ok := x.Value.(*Val_U64Val); ok {
			return x.U64Val
		}
	}
	return 0
}

func (x *Val) GetF32Val() float32 {
	if x != nil {
		if x, ok := x.Value.(*Val_F32Val); ok {
			return x.F32Val
		}
	}
	return 0
}

func (x *Val) GetF64Val() float64 {
	if x != nil {
		if x, ok := x.Value.(*Val_F64Val); ok {
			return x.F64Val
		}
	}
	return 0
}

func (x *Val) GetCharVal() uint32 {
	if x != nil {
		if x, ok := x.Value.(*Val_CharVal); ok {
			return x.CharVal
		}
	}
	return 0
}

func (x *Val) GetStringVal() string {
	if x != nil {
		if x, ok := x.Value.(*Val_StringVal); ok {
			return x.StringVal
		}
	}
	return ""
}

func (x *Val) GetListVal() *ListVal {
	if x != nil {
		if x, ok := x.Value.(*Val_ListVal); ok {
			return x.ListVal
		}
	}
	return nil
}

func (x *Val) GetTupleVal() *TupleVal {
	if x != nil {
		if x, ok := x.Value.(*Val_TupleVal); ok {
			return x.TupleVal
		}
	}
	return nil
}

func (x *Val) GetOptionVal() *OptionVal {
	if x != nil {
		if x, ok := x.Value.(*Val_OptionVal); ok {
			return x.OptionVal
		}
	}
	return nil
}

func (x *Val) GetResultVal() *ResultVal {
	if x != nil {
		if x, ok := x.Value.(*Val_ResultVal); ok {
			return x.ResultVal
		}
	}
	return nil
}

func (x *Val) GetRecordVal() *RecordVal {
	if x != nil {
		if x, ok := x.Value.(*Val_RecordVal); ok {
			return x.RecordVal
		}
	}
	return nil
}

func (x *Val) GetVariantVal() *VariantVal {
	if x != nil {
		if x, ok := x.Value.(*Val_VariantVal); ok {
			return x.VariantVal
		}
	}
	return nil
}

func (x *Val) GetEnumVal() string {
	if x != nil {
		if x, ok := x.Value.(*Val_EnumVal); ok {
			return x.EnumVal
		}
	}
	return ""
}

func (x *Val) GetFlagsVal() *FlagsVal {
	if x != nil {
		if x, ok := x.Value.(*Val_FlagsVal); ok {
			return x.FlagsVal
		}
	}
	return nil
}

type isVal_Value interface {
	isVal_Value()
}

type Val_BoolVal struct {
	// Primitive types
	BoolVal bool `protobuf:"varint,1,opt,name=bool_val,json=boolVal,proto3,oneof"`
}

type Val_S8Val struct {
	S8Val int32 `protobuf:"zigzag32,2,opt,name=s8_val,json=s8Val,proto3,oneof"` // s8
}

type Val_U8Val struct {
	U8Val uint32 `protobuf:"varint,3,opt,name=u8_val,json=u8Val,proto3,oneof"` // u8
}

type Val_S16Val struct {
	S16Val int32 `protobuf:"zigzag32,4,opt,name=s16_val,json=s16Val,proto3,oneof"` // s16
}

type Val_U16Val struct {
	U16Val uint32 `protobuf:"varint,5,opt,name=u16_val,json=u16Val,proto3,oneof"` // u16
}

type Val_S32Val struct {
	S32Val int32 `protobuf:"zigzag32,6,opt,name=s32_val,json=s32Val,proto3,oneof"` // s32
}

type Val_U32Val struct {
	U32Val uint32 `protobuf:"varint,7,opt,name=u32_val,json=u32Val,proto3,oneof"` // u32
}

type Val_S64Val struct {
	S64Val int64 `protobuf:"zigzag64,8,opt,name=s64_val,json=s64Val,proto3,oneof"` // s64
}

type Val_U64Val struct {
	U64Val uint64 `protobuf:"varint,9,opt,name=u64_val,json=u64Val,proto3,oneof"` // u64
}

type Val_F32Val struct {
	F32Val float32 `protobuf:"fixed32,10,opt,name=f32_val,json=f32Val,proto3,oneof"` // f32
}

type Val_F64Val struct {
	F64Val float64 `protobuf:"fixed64,11,opt,name=f64_val,json=f64Val,proto3,oneof"` // f64
}

type Val_CharVal struct {
	CharVal uint32 `protobuf:"varint,12,opt,name=char_val,json=charVal,proto3,oneof"` // char — Unicode scalar value (0..=0x10FFFF)
}

type Val_StringVal struct {
	StringVal string `protobuf:"bytes,13,opt,name=string_val,json=stringVal,proto3,oneof"` // string
}

type Val_ListVal struct {
	// Compound built-in types
	ListVal *ListVal `protobuf:"bytes,14,opt,name=list_val,json=listVal,proto3,oneof"` // list<T>
}

type Val_TupleVal struct {
	TupleVal *TupleVal `protobuf:"bytes,15,opt,name=tuple_val,json=tupleVal,proto3,oneof"` // tuple<T0, T1, ...>
}

type Val_OptionVal struct {
	OptionVal *OptionVal `protobuf:"bytes,16,opt,name=option_val,json=optionVal,proto3,oneof"` // option<T>
}

type Val_ResultVal struct {
	ResultVal *ResultVal `protobuf:"bytes,17,opt,name=result_val,json=resultVal,proto3,oneof"` // result<T, E>
}

type Val_RecordVal struct {
	// User-defined types
	RecordVal *RecordVal `protobuf:"bytes,18,opt,name=record_val,json=recordVal,proto3,oneof"` // record { name: T, ... }
}

type Val_VariantVal struct {
	VariantVal *VariantVal `protobuf:"bytes,19,opt,name=variant_val,json=variantVal,proto3,oneof"` // variant { case(T?), ... }
}

type Val_EnumVal struct {
	EnumVal string `protobuf:"bytes,20,opt,name=enum_val,json=enumVal,proto3,oneof"` // enum { case, ... }  — carries the case name
}

type Val_FlagsVal struct {
	FlagsVal *FlagsVal `protobuf:"bytes,21,opt,name=flags_val,json=flagsVal,proto3,oneof"` // flags { name, ... } — set of active flag names
}

func (*Val_BoolVal) isVal_Value() {}

func (*Val_S8Val) isVal_Value() {}

func (*Val_U8Val) isVal_Value() {}

func (*Val_S16Val) isVal_Value() {}

func (*Val_U16Val) isVal_Value() {}

func (*Val_S32Val) isVal_Value() {}

func (*Val_U32Val) isVal_Value() {}

func (*Val_S64Val) isVal_Value() {}

func (*Val_U64Val) isVal_Value() {}

func (*Val_F32Val) isVal_Value() {}

func (*Val_F64Val) isVal_Value() {}

func (*Val_CharVal) isVal_Value() {}

func (*Val_StringVal) isVal_Value() {}

func (*Val_ListVal) isVal_Value() {}

func (*Val_TupleVal) isVal_Value() {}

func (*Val_OptionVal) isVal_Value() {}

func (*Val_ResultVal) isVal_Value() {}

func (*Val_RecordVal) isVal_Value() {}

func (*Val_VariantVal) isVal_Value() {}

func (*Val_EnumVal) isVal_Value() {}

func (*Val_FlagsVal) isVal_Value() {}

// list<T> — ordered sequence of values
type ListVal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Val                 `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVal) Reset() {
	*x = ListVal{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVal) ProtoMessage() {}

func (x *ListVal) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVal.ProtoReflect.Descriptor instead.
func (*ListVal) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *ListVal) GetValues() []*Val {
	if x != nil {
		return x.Values
	}
	return nil
}

// tuple<T0, T1, ...> — fixed-length ordered sequence
type TupleVal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Val                 `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TupleVal) Reset() {
	*x = TupleVal{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleVal) ProtoMessage() {}

func (x *TupleVal) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleVal.ProtoReflect.Descriptor instead.
func (*TupleVal) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *TupleVal) GetValues() []*Val {
	if x != nil {
		return x.Values
	}
	return nil
}

// option<T> — absent value field means none; present means some(value)
type OptionVal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Val                   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionVal) Reset() {
	*x = OptionVal{}
	mi := &file_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionVal) ProtoMessage() {}

func (x *OptionVal) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionVal.ProtoReflect.Descriptor instead.
func (*OptionVal) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{4}
}

func (x *OptionVal) GetValue() *Val {
	if x != nil {
		return x.Value
	}
	return nil
}

// result<T, E> — is_ok=true → ok case, is_ok=false → err case;
// value is absent when the case carries no payload (unit)
type ResultVal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOk          bool                   `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	Value         *Val                   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultVal) Reset() {
	*x = ResultVal{}
	mi := &file_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultVal) ProtoMessage() {}

func (x *ResultVal) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultVal.ProtoReflect.Descriptor instead.
func (*ResultVal) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{5}
}

func (x *ResultVal) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *ResultVal) GetValue() *Val {
	if x != nil {
		return x.Value
	}
	return nil
}

// record { field-name: T, ... } — named fields in declaration order
type RecordVal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*RecordField         `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordVal) Reset() {
	*x = RecordVal{}
	mi := &file_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordVal) ProtoMessage() {}

func (x *RecordVal) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordVal.ProtoReflect.Descriptor instead.
func (*RecordVal) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{6}
}

func (x *RecordVal) GetFields() []*RecordField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type RecordField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         *Val                   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordField) Reset() {
	*x = RecordField{}
	mi := &file_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordField) ProtoMessage() {}

func (x *RecordField) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordField.ProtoReflect.Descriptor instead.
func (*RecordField) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{7}
}

func (x *RecordField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecordField) GetValue() *Val {
	if x != nil {
		return x.Value
	}
	return nil
}

// variant { case-name(T?), ... } — active case name plus optional payload
type VariantVal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         *Val                   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // absent if the case carries no payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariantVal) Reset() {
	*x = VariantVal{}
	mi := &file_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantVal) ProtoMessage() {}

func (x *VariantVal) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantVal.ProtoReflect.Descriptor instead.
func (*VariantVal) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{8}
}

func (x *VariantVal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VariantVal) GetValue() *Val {
	if x != nil {
		return x.Value
	}
	return nil
}

// flags { flag-name, ... } — names of all active (set) flags
type FlagsVal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         []string               `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagsVal) Reset() {
	*x = FlagsVal{}
	mi := &file_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagsVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagsVal) ProtoMessage() {}

func (x *FlagsVal) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagsVal.ProtoReflect.Descriptor instead.
func (*FlagsVal) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{9}
}

func (x *FlagsVal) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

type EnvironmentVariable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentVariable) Reset() {
	*x = EnvironmentVariable{}
	mi := &file_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentVariable) ProtoMessage() {}

func (x *EnvironmentVariable) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentVariable.ProtoReflect.Descriptor instead.
func (*EnvironmentVariable) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{10}
}

func (x *EnvironmentVariable) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EnvironmentVariable) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Task struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Function             *FunctionIdentifier    `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	Parameters           []*Val                 `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	Arguments            []string               `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	EnvironmentVariables []*EnvironmentVariable `protobuf:"bytes,4,rep,name=environment_variables,json=environmentVariables,proto3" json:"environment_variables,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{11}
}

func (x *Task) GetFunction() *FunctionIdentifier {
	if x != nil {
		return x.Function
	}
	return nil
}

func (x *Task) GetParameters() []*Val {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Task) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *Task) GetEnvironmentVariables() []*EnvironmentVariable {
	if x != nil {
		return x.EnvironmentVariables
	}
	return nil
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\x12\x04task\x1a\x0eregistry.proto\"\x80\x01\n" +
	"\x12FunctionIdentifier\x128\n" +
	"\bartifact\x18\x01 \x01(\v2\x1c.registry.ArtifactIdentifierR\bartifact\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xe5\x05\n" +
	"\x03Val\x12\x1b\n" +
	"\bbool_val\x18\x01 \x01(\bH\x00R\aboolVal\x12\x17\n" +
	"\x06s8_val\x18\x02 \x01(\x11H\x00R\x05s8Val\x12\x17\n" +
	"\x06u8_val\x18\x03 \x01(\rH\x00R\x05u8Val\x12\x19\n" +
	"\as16_val\x18\x04 \x01(\x11H\x00R\x06s16Val\x12\x19\n" +
	"\au16_val\x18\x05 \x01(\rH\x00R\x06u16Val\x12\x19\n" +
	"\as32_val\x18\x06 \x01(\x11H\x00R\x06s32Val\x12\x19\n" +
	"\au32_val\x18\a \x01(\rH\x00R\x06u32Val\x12\x19\n" +
	"\as64_val\x18\b \x01(\x12H\x00R\x06s64Val\x12\x19\n" +
	"\au64_val\x18\t \x01(\x04H\x00R\x06u64Val\x12\x19\n" +
	"\af32_val\x18\n" +
	" \x01(\x02H\x00R\x06f32Val\x12\x19\n" +
	"\af64_val\x18\v \x01(\x01H\x00R\x06f64Val\x12\x1b\n" +
	"\bchar_val\x18\f \x01(\rH\x00R\acharVal\x12\x1f\n" +
	"\n" +
	"string_val\x18\r \x01(\tH\x00R\tstringVal\x12*\n" +
	"\blist_val\x18\x0e \x01(\v2\r.task.ListValH\x00R\alistVal\x12-\n" +
	"\ttuple_val\x18\x0f \x01(\v2\x0e.task.TupleValH\x00R\btupleVal\x120\n" +
	"\n" +
	"option_val\x18\x10 \x01(\v2\x0f.task.OptionValH\x00R\toptionVal\x120\n" +
	"\n" +
	"result_val\x18\x11 \x01(\v2\x0f.task.ResultValH\x00R\tresultVal\x120\n" +
	"\n" +
	"record_val\x18\x12 \x01(\v2\x0f.task.RecordValH\x00R\trecordVal\x123\n" +
	"\vvariant_val\x18\x13 \x01(\v2\x10.task.VariantValH\x00R\n" +
	"variantVal\x12\x1b\n" +
	"\benum_val\x18\x14 \x01(\tH\x00R\aenumVal\x12-\n" +
	"\tflags_val\x18\x15 \x01(\v2\x0e.task.FlagsValH\x00R\bflagsValB\a\n" +
	"\x05value\",\n" +
	"\aListVal\x12!\n" +
	"\x06values\x18\x01 \x03(\v2\t.task.ValR\x06values\"-\n" +
	"\bTupleVal\x12!\n" +
	"\x06values\x18\x01 \x03(\v2\t.task.ValR\x06values\",\n" +
	"\tOptionVal\x12\x1f\n" +
	"\x05value\x18\x01 \x01(\v2\t.task.ValR\x05value\"A\n" +
	"\tResultVal\x12\x13\n" +
	"\x05is_ok\x18\x01 \x01(\bR\x04isOk\x12\x1f\n" +
	"\x05value\x18\x02 \x01(\v2\t.task.ValR\x05value\"6\n" +
	"\tRecordVal\x12)\n" +
	"\x06fields\x18\x01 \x03(\v2\x11.task.RecordFieldR\x06fields\"B\n" +
	"\vRecordField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\x05value\x18\x02 \x01(\v2\t.task.ValR\x05value\"A\n" +
	"\n" +
	"VariantVal\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\x05value\x18\x02 \x01(\v2\t.task.ValR\x05value\" \n" +
	"\bFlagsVal\x12\x14\n" +
	"\x05flags\x18\x01 \x03(\tR\x05flags\"=\n" +
	"\x13EnvironmentVariable\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xd5\x01\n" +
	"\x04Task\x124\n" +
	"\bfunction\x18\x01 \x01(\v2\x18.task.FunctionIdentifierR\bfunction\x12)\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2\t.task.ValR\n" +
	"parameters\x12\x1c\n" +
	"\targuments\x18\x03 \x03(\tR\targuments\x12N\n" +
	"\x15environment_variables\x18\x04 \x03(\v2\x19.task.EnvironmentVariableR\x14environmentVariablesB\fZ\n" +
	"proto_gen/b\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_task_proto_goTypes = []any{
	(*FunctionIdentifier)(nil),  // 0: task.FunctionIdentifier
	(*Val)(nil),                 // 1: task.Val
	(*ListVal)(nil),             // 2: task.ListVal
	(*TupleVal)(nil),            // 3: task.TupleVal
	(*OptionVal)(nil),           // 4: task.OptionVal
	(*ResultVal)(nil),           // 5: task.ResultVal
	(*RecordVal)(nil),           // 6: task.RecordVal
	(*RecordField)(nil),         // 7: task.RecordField
	(*VariantVal)(nil),          // 8: task.VariantVal
	(*FlagsVal)(nil),            // 9: task.FlagsVal
	(*EnvironmentVariable)(nil), // 10: task.EnvironmentVariable
	(*Task)(nil),                // 11: task.Task
	(*ArtifactIdentifier)(nil),  // 12: registry.ArtifactIdentifier
}
var file_task_proto_depIdxs = []int32{
	12, // 0: task.FunctionIdentifier.artifact:type_name -> registry.ArtifactIdentifier
	2,  // 1: task.Val.list_val:type_name -> task.ListVal
	3,  // 2: task.Val.tuple_val:type_name -> task.TupleVal
	4,  // 3: task.Val.option_val:type_name -> task.OptionVal
	5,  // 4: task.Val.result_val:type_name -> task.ResultVal
	6,  // 5: task.Val.record_val:type_name -> task.RecordVal
	8,  // 6: task.Val.variant_val:type_name -> task.VariantVal
	9,  // 7: task.Val.flags_val:type_name -> task.FlagsVal
	1,  // 8: task.ListVal.values:type_name -> task.Val
	1,  // 9: task.TupleVal.values:type_name -> task.Val
	1,  // 10: task.OptionVal.value:type_name -> task.Val
	1,  // 11: task.ResultVal.value:type_name -> task.Val
	7,  // 12: task.RecordVal.fields:type_name -> task.RecordField
	1,  // 13: task.RecordField.value:type_name -> task.Val
	1,  // 14: task.VariantVal.value:type_name -> task.Val
	0,  // 15: task.Task.function:type_name -> task.FunctionIdentifier
	1,  // 16: task.Task.parameters:type_name -> task.Val
	10, // 17: task.Task.environment_variables:type_name -> task.EnvironmentVariable
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	file_registry_proto_init()
	file_task_proto_msgTypes[1].OneofWrappers = []any{
		(*Val_BoolVal)(nil),
		(*Val_S8Val)(nil),
		(*Val_U8Val)(nil),
		(*Val_S16Val)(nil),
		(*Val_U16Val)(nil),
		(*Val_S32Val)(nil),
		(*Val_U32Val)(nil),
		(*Val_S64Val)(nil),
		(*Val_U64Val)(nil),
		(*Val_F32Val)(nil),
		(*Val_F64Val)(nil),
		(*Val_CharVal)(nil),
		(*Val_StringVal)(nil),
		(*Val_ListVal)(nil),
		(*Val_TupleVal)(nil),
		(*Val_OptionVal)(nil),
		(*Val_ResultVal)(nil),
		(*Val_RecordVal)(nil),
		(*Val_VariantVal)(nil),
		(*Val_EnumVal)(nil),
		(*Val_FlagsVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
