host: localhost:8080 (default)
info:
  contact: {}
  description: API Central Entrypoint for the Enclave Platform
  license:
    name: GNU General Public License v3.0
    url: https://www.gnu.org/licenses/gpl-3.0.html
  title: Enclave API Server
  version: v0.0.0
paths:
  /ready:
    get:
      consumes:
      - application/json
      description: Health-Check to see if the Api-Server is reachable / ready
      produces:
      - application/json
      responses:
        "200":
          description: '{status: ready}'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health-Check Endpoint
      tags:
      - system
swagger: "2.0"
